name: flutter_inus_pray
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.0+9
  cloud_firestore: ^0.12.9+6
  animated_text_kit: ^1.3.1
  modal_progress_hud: ^0.1.3
  logger: ^0.7.0+2
  flutter_statusbarcolor: ^0.2.3
  flutter_kakao_login: "^0.5.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - res/images/
    - res/icons/
