name: flutter_inus_pray
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.3
  firebase_auth: ^0.15.2
  cloud_firestore: ^0.13.0+1
  firebase_messaging: ^6.0.16
  firebase_storage: ^3.1.1
  animated_text_kit: ^1.3.1
  modal_progress_hud: ^0.1.3
  flutter_statusbarcolor: ^0.2.3
  flutter_kakao_login: "^0.5.0"
  shared_preferences: ^0.5.4+6
  provider: ^3.2.0
  flutter_spinkit: "^4.1.0"
  fluttertoast: ^3.1.3
  font_awesome_flutter: ^8.5.0
  image_picker: ^0.6.2+3
  flutter_slidable: "^0.5.4"
  image_cropper: ^1.1.1
  firebase_admob: ^0.9.3+2
  share: ^0.6.4+3
  http: ^0.12.1
  flutter_swiper: ^1.1.6
  url_launcher: ^5.4.10
  sign_in_with_apple: ^2.5.0

dev_dependencies:
  flutter_native_splash: ^0.1.9
  flutter_test:
    sdk: flutter

flutter_native_splash:
  image: res/images/splash.png
  color: "FFFFFF"

flutter:
  uses-material-design: true

  assets:
    - res/images/
    - res/icons/
